FROM archlinux:latest

# Update all system packages and dependencies
RUN pacman -Syu --noconfirm \
    git \
    cmake \
    ninja \
    base-devel \
    cuda \
    ffmpeg \
    pkgconf \
    curl

# Add CUDA binaries to PATH and set the Toolkit root for CMake
ENV PATH="/opt/cuda/bin:${PATH}"
ENV CUDAToolkit_ROOT="/opt/cuda"

RUN git clone https://github.com/Neroued/ninfer.git /app/ninfer

WORKDIR /app/ninfer

RUN cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release
RUN cmake --build build -j
